spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.10:3306/TakeAway?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=true
    username: root
    password: root
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true